### PR TITLE
Enable Prometheus backend and JVM metrics via sysprops

### LINKED ISSUE #45: Activate Prometheus backend via sysprop
It would be nice to be able to activate the Prometheus backend via sysprops.

Also, all JVM metrics.

### PR DESCRIPTION
**Pull request by tsegismont**
Fixes #45

### CODE REVIEW

**Comment by tsegismont** [comment]
@cescoffier can you please take a look?

This PR uses the Vert.x Metrics factory class as a hook to configure options via sysprops.

I noticed these logs during testing:

```
[main] 2018-10-17T15:06:11.219+02:00 WARNING [io.vertx.core.impl.launcher.commands.RunCommand]  No such property to configure on options: io.vertx.micrometer.MicrometerMetricsOptions.prometheus.enabled
[main] 2018-10-17T15:06:11.265+02:00 WARNING [io.vertx.core.impl.launcher.commands.RunCommand]  No such property to configure on options: io.vertx.micrometer.MicrometerMetricsOptions.prometheus.port
[main] 2018-10-17T15:06:12.572+02:00 WARNING [io.vertx.core.impl.launcher.commands.RunCommand]  No such property to configure on options: io.vertx.micrometer.MicrometerMetricsOptions.jvm.enabled
```

@cescoffier I think these logs could be reduced to debug level. Is that fine with you.

**Comment by cescoffier** [comment]
Agreed, these log messages are a bit weird. To you pass the `-D` before or after the main class?

**Comment by tsegismont** [comment]
> Agreed, these log messages are a bit weird. To you pass the -D before or after the main class?

Before. These logs come from `BareCommand#configureFromSystemProperties `, which complains because it expects sysprops with the metrics options prefix to point to a options field.

**Comment by tsegismont** [comment]
See #45  (closed in favor of eclipse-vertx/vert.x#1729)

**Pull request closed without merging**
