### PR TITLE
Implement custom tags provider for HTTP Client metrics

### PR DESCRIPTION
**Pull request by jordillachmrf**
Related to https://github.com/vert-x3/vertx-micrometer-metrics/issues/133
@jotak  My Eclipse user is jllachf and I've linked my github account to it. Do I really need to set up a new Eclipse account ?

### CODE REVIEW

**Comment by vietj** [comment]
can you sign the Eclipse Contributor Agreement @jordillachmrf

**Comment by jordillachmrf** [comment]
Hi @vietj ,  I already signed it with my user, jllachf, and linked this user to my github's account @jordillachmrf  ... do I really have to create a new user and sign the agreement ?

**Comment by jordillachmrf** [comment]
Due to lack of feedback I created a new account and accepted the agreement

**Comment by jotak** [comment]
Thank you @jordillachmrf ! This looks overall good to me, just two things:
- it should be documented (in `src/main/asciidoc/index.adoc`)
- I think we should rename the existing option for server-side (keeping but deprecating the current name), to make the two more consistent and obvious. @vietj , agree? (I can take care of that after this Pr is merged)

About the doc, currently we have this:

```
=== Custom tags provider

You can define a function that generates additional tags (or labels) for HTTP server metrics.
Such function takes an {@link io.vertx.core.spi.observability.HttpRequest} object as a parameter, and returns
an Iterable of {@link io.micrometer.core.instrument.Tag}.

As an example, here is how to map the _x-user_ header to a custom label _user_:

[source,$lang]
----
{@link examples.MicrometerMetricsExamples#useCustomTagsProvider()}
----
```

Suggestion: change it to (changes marked with `**`):

```
=== Custom tags provider

You can define a function that generates additional tags (or labels) for HTTP server **or client** metrics.
Such function takes an {@link io.vertx.core.spi.observability.HttpRequest} object as a parameter, and returns
an Iterable of {@link io.micrometer.core.instrument.Tag}.

As an example, here is how to map the _x-user_ header to a custom label _user_ **in both server and client** metrics:

[source,$lang]
----
{@link examples.MicrometerMetricsExamples#useCustomTagsProvider()}
----
```
And updating the linked example to include client metrics

**Comment by jordillachmrf** [comment]
@jotak I have not changed the way tests are setup but test MetricsServiceImplTest is failing due to
```
  Run 1: MetricsServiceImplTest.shouldGetSnapshotWithV3Names » Bind Address already in ...
  Run 2: MetricsServiceImplTest.shouldGetSnapshotWithV3Names » Bind Address already in ...
```
who will take care of this ?

**Comment by jotak** [comment]
@vietj I see several runs of a given test in the CI job, is that something changed in `VertxUnitRunner.class`, or something? It triggers errors with address already in use. Until now we did not need to specify port randomly in tests, as we properly cleanup everything on test teardown ( `vertx.close(context.asyncAssertSuccess());`) . It is not sufficient anymore?

**Comment by jordillachmrf** [comment]
hey team! can I do anything to speed up things ?

**Comment by vietj** [comment]
I don't know what changed, I think we should ping @jponge on the subject

**Comment by vietj** [comment]
it seems that CI is green, can you rebase on latest master ?

**Comment by jordillachmrf** [comment]
Closing this one in favour of https://github.com/vert-x3/vertx-micrometer-metrics/pull/135

**Pull request closed without merging**
