### PR TITLE
Bump micrometer from 1.6.2  to 1.8.4

### PR DESCRIPTION
**Pull request by yeikel**
Motivation:

Maintenance/ Keep dependencies up to date

### CODE REVIEW

**Comment by tsegismont** [comment]
@yeikel on the vertx user group you said you add issues with metrics when upgrading to this version but it seems our test suite does not detect any regression.

Can you elaborate about the issues?

**Comment by yeikel** [comment]
> @yeikel on the vertx user group you said you add issues with metrics when upgrading to this version but it seems our test suite does not detect any regression.
> 
> Can you elaborate on the issues?




@tsegismont 

Are you referring to
 https://groups.google.com/g/vertx/c/9mCsl4rKhhc/m/Jaeh64rPAQAJ?


I am not the one who reported problems with this version. The email you're referring to was signed by "Clive"

**Comment by tsegismont** [comment]
@yeikel yes I was. Sorry for the confusion.

**Comment by yeikel** [comment]
> @yeikel yes I was. Sorry for the confusion.

No problem! Thank you for checking

Let me know if you publish any snapshot for this upgrade so I can also test it as well

**Comment by tsegismont** [comment]
I'm waiting for a reply from the user. Besides, this would be a Vert.x
4.3.0 upgrade so I can't merge yet (master branches still target 4.2).

Anyway, given this is a simple POM version, you could test right away by
changing the micrometer dependencies in your project's POM file.

**Comment by yeikel** [comment]
Please note that `1.8.3` was just released and I just updated this PR instead

**Comment by yeikel** [comment]
Note that `1.8.4` was just released and I updated the PR instead

**Review by tsegismont — APPROVED** [review]
Thank you @yeikel

**Pull request merged**
