### PR TITLE
Bump micrometer from 1.8.4 to 1.9.3

### PR DESCRIPTION
**Pull request by yeikel**

### CODE REVIEW

**Review by tsegismont — APPROVED** [review]

**Comment by tsegismont** [comment]
Hi @jotak it seems some tests are often failing on CI (bind address already in use). Does that ring a bell?

**Comment by yeikel** [comment]
We should probably bind to port 0 to avoid this

**Comment by jotak** [comment]
@tsegismont I mentioned this a while back: https://github.com/vert-x3/vertx-micrometer-metrics/pull/134#issuecomment-1043009884 honestly I don't know why it's failing despite everything apparently cleanup properly on tear down; I'm sorry but I don't have time to investigate :(

**Comment by yeikel** [comment]
Note that 1.9.3 is out and I just updated the PR

**Pull request merged**
