### PR TITLE
Added support for customizing Prometheus request for metrics scraping by introducing PrometheusRequestHandler

### PR DESCRIPTION
**Pull request by swamymavuri**
Motivation:

This feature aims to enhance the customization options for Prometheus request handling by introducing the PrometheusRequestHandler. This handler provides users with the ability to define their own request handling strategies tailored to their application's needs, enabling greater flexibility and control over how Prometheus metrics are scraped and served.

Conformance:

Your commits should be signed and you should have signed the Eclipse Contributor Agreement as explained in https://github.com/eclipse/vert.x/blob/master/CONTRIBUTING.md
Please also make sure you adhere to the code style guidelines: https://github.com/vert-x3/wiki/wiki/Vert.x-code-style-guidelines

### CODE REVIEW

**Comment by swamymavuri** [comment]
Hi @tsegismont ,
Unfortunately i need to close the previous pull request because of the merge conflict with the `PrometheusBackendRegistry`.
i should fetch it from the upstream instead of syncing the fork.

Here is the link with the previous comments which you have suggested 
https://github.com/vert-x3/vertx-micrometer-metrics/issues/213

Raised this new PR addressing all the suggestions.

Thanks

**Review by tsegismont — COMMENTED** [review]
Thank you @swamymavuri 

I notice you added examples, but this is only useful if you update the Asciidoc file to include them. Have you planned to do this in a follow-up commit?

To be honest, I think only one example like for the `PrometheusScrapingHandler` is enough.

**Comment by swamymavuri** [comment]
> Thank you @swamymavuri
> 
> I notice you added examples, but this is only useful if you update the Asciidoc file to include them. Have you planned to do this in a follow-up commit?
> 
> To be honest, I think only one example like for the `PrometheusScrapingHandler` is enough.

Thank you @tsegismont,

I have added the Asciidoc documentation and updated the examples accordingly. Please review the changes and let me know if any further adjustments are needed.

**Comment by swamymavuri** [comment]
> I've merged the PR with minor changes

Thank you @tsegismont

**Pull request merged**
