### PR TITLE
Upgrade to Micrometer 1.14.0

### PR DESCRIPTION
**Pull request by jponge**
https://github.com/micrometer-metrics/micrometer/releases/tag/v1.14.0

### CODE REVIEW

**Comment by jponge** [comment]
@tsegismont  Note: we've had issues for months with Micrometer on the `4.x` branch, I'm looking at how to backport unless Vert.x 4 releases shall stay on an earlier Micrometer version.

**Comment by tsegismont** [comment]
> Note: we've had issues for months with Micrometer on the `4.x` branch,

Can you elaborate? I can see only green builds on this branch.

> I'm looking at how to backport unless Vert.x 4 releases shall stay on an earlier Micrometer version.

Backporting may be possible but not trivially. The Prometheus registry has breaking changes between 1.12 and 1.13 unfortunately.

**Review by tsegismont — APPROVED** [review]
Thank you @jponge , looks good to me !

**Comment by jponge** [comment]
Since Quarkus is on 1.13 and probably soon on 1.14, I think we need to align across Vert.x 4 + the Vert.x Mutiny bindings https://github.com/quarkusio/quarkus/blob/main/bom/application/pom.xml#L36 

@cescoffier can you confirm that it's a backport to do?

**Pull request merged**
