### PR TITLE
Add documentation for percentiles

### PR DESCRIPTION
**Pull request by jotak**
cc @cescoffier => related to https://github.com/vert-x3/vertx-micrometer-metrics/issues/52

### CODE REVIEW

**Comment by cescoffier** [comment]
Great! 

Wondering if we can avoid the downcasting of the registry, something like: `withPercentiles` that would to the work.

**Comment by jotak** [comment]
You mean, using our own Metrics options instead above the micrometer's registry?

Currently our options are just wrapping the micrometer registry and provide some handful shortcuts for some micrometer internal configs, but it's not 1-to-1 (many micrometer options are not reflected into vertx metrics options) so in many cases it's still necessary to have a direct access to the micrometer registry.

The advantage of configuring directly the micrometer registry is that you'll have more options / more control. Ex: here in the example I show how to activate all percentiles, which leads to many additional timeseries that are stored, but a user could fine-tune with only a smaller subset, like limited to 0.95 and 0.99, which will save a lot of space:

```
    registry.config().meterFilter(
        new MeterFilter() {
          @Override
          public DistributionStatisticConfig configure(Meter.Id id, DistributionStatisticConfig config) {
            return DistributionStatisticConfig.builder()
                .percentiles(0.95, 0.99)
                .build()
                .merge(config);
          }
        });
```

And there's still other options like slas... so at some point I prefer to guide the user through fine-tuning the micrometer registry (and delegate the responsibility of configuration to it) so that he gets full control of it.

**Comment by jotak** [comment]
As it's only doc & example update, is it ok to merge now ? (regarding 3.6 release)
Needs a 3.6 branch or is it fine to put only in master? (cc @vietj )

**Comment by tsegismont** [comment]
@jotak I'm fine with merging. But I believe it would be useful to have a switch (disabled by default) in options to enable statistics with sensible defaults. This documentation will not be wasted as it will show how to proceed for fine tuning.

**Comment by jotak** [comment]
@tsegismont so i'm merging, and working on a separate PR for the option

**Pull request merged**
